CREATE TABLE `schedule_occurrences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduleId` int NOT NULL,
	`employeeId` int,
	`type` enum('late','early_exit','absence','client_issue','other','critical') NOT NULL,
	`description` text NOT NULL,
	`autoGenerated` boolean NOT NULL DEFAULT false,
	`resolved` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int NOT NULL,
	CONSTRAINT `schedule_occurrences_id` PRIMARY KEY(`id`)
);
