import { z } from "zod";
import { protectedProcedure, router } from "../../_core/trpc";
import { desc, eq, and, inArray } from "drizzle-orm";
import { getDb } from "../../db";
import { employees, users, scheduleOccurrences } from "../../../drizzle/schema";
import { TRPCError } from "@trpc/server";
import {
  OCCURRENCE_TYPES,
  getOccurrenceTypeLabel,
} from "../../lib/schedule-occurrences";
import { isLeaderOfSchedule } from "./_shared";

export const occurrencesRouter = router({
  listOccurrences: protectedProcedure
    .input(z.number())
    .query(async ({ ctx, input }) => {
      const isLeader = await isLeaderOfSchedule(ctx.user.id, input);
      if (!isLeader) throw new TRPCError({ code: "FORBIDDEN", message: "Você não é o líder deste planejamento" });

      const db = await getDb();
      if (!db) return [];

      const occurrences = await db
        .select()
        .from(scheduleOccurrences)
        .where(eq(scheduleOccurrences.scheduleId, input))
        .orderBy(desc(scheduleOccurrences.createdAt));

      const employeeIds = Array.from(new Set(occurrences.map(o => o.employeeId).filter((id): id is number => typeof id === "number")));
      const createdByIds = Array.from(new Set(occurrences.map(o => o.createdBy).filter((id): id is number => typeof id === "number")));

      const [employeesList, usersList] = await Promise.all([
        employeeIds.length > 0 ? db.select().from(employees).where(inArray(employees.id, employeeIds)) : Promise.resolve([]),
        createdByIds.length > 0 ? db.select().from(users).where(inArray(users.id, createdByIds)) : Promise.resolve([]),
      ]);

      const employeeMap = Object.fromEntries(employeesList.map(e => [e.id, e]));
      const userMap = Object.fromEntries(usersList.map(u => [u.id, u]));

      return occurrences.map(item => ({
        ...item,
        employeeName: item.employeeId ? employeeMap[item.employeeId]?.name || "—" : "Operação",
        createdByName: typeof item.createdBy === "number" ? userMap[item.createdBy]?.name || "Sistema" : "Sistema",
        typeLabel: getOccurrenceTypeLabel(item.type),
      }));
    }),

  addOccurrence: protectedProcedure
    .input(z.object({
      scheduleId: z.number(),
      employeeId: z.number().optional(),
      type: z.enum(OCCURRENCE_TYPES),
      description: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const isLeader = await isLeaderOfSchedule(ctx.user.id, input.scheduleId);
      if (!isLeader) throw new TRPCError({ code: "FORBIDDEN", message: "Voce nao e o lider deste planejamento" });

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const [result] = await db.insert(scheduleOccurrences).values({
        scheduleId: input.scheduleId,
        employeeId: input.employeeId ?? null,
        type: input.type,
        description: input.description?.trim() || null,
        autoGenerated: false,
        resolved: false,
        createdBy: ctx.user.id,
      });

      return { id: Number(result.insertId), success: true };
    }),

  updateOccurrence: protectedProcedure
    .input(z.object({
      occurrenceId: z.number(),
      scheduleId: z.number(),
      employeeId: z.number().optional(),
      type: z.enum(OCCURRENCE_TYPES),
      description: z.string().min(3),
    }))
    .mutation(async ({ ctx, input }) => {
      const isLeader = await isLeaderOfSchedule(ctx.user.id, input.scheduleId);
      if (!isLeader) throw new TRPCError({ code: "FORBIDDEN", message: "Você não é o líder deste planejamento" });

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      await db.update(scheduleOccurrences)
        .set({ employeeId: input.employeeId ?? null, type: input.type, description: input.description.trim() })
        .where(and(eq(scheduleOccurrences.id, input.occurrenceId), eq(scheduleOccurrences.scheduleId, input.scheduleId)));

      return { success: true };
    }),

  deleteOccurrence: protectedProcedure
    .input(z.object({ occurrenceId: z.number(), scheduleId: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const isLeader = await isLeaderOfSchedule(ctx.user.id, input.scheduleId);
      if (!isLeader) throw new TRPCError({ code: "FORBIDDEN", message: "Você não é o líder deste planejamento" });

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      await db.delete(scheduleOccurrences)
        .where(and(eq(scheduleOccurrences.id, input.occurrenceId), eq(scheduleOccurrences.scheduleId, input.scheduleId)));

      return { success: true };
    }),

  resolveOccurrence: protectedProcedure
    .input(z.object({ occurrenceId: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const [occurrence] = await db.select().from(scheduleOccurrences).where(eq(scheduleOccurrences.id, input.occurrenceId)).limit(1);
      if (!occurrence) throw new TRPCError({ code: "NOT_FOUND", message: "Ocorrencia nao encontrada" });

      const isLeader = await isLeaderOfSchedule(ctx.user.id, occurrence.scheduleId);
      if (!isLeader) throw new TRPCError({ code: "FORBIDDEN", message: "Você não é o líder deste planejamento" });

      await db.update(scheduleOccurrences).set({ resolved: true }).where(eq(scheduleOccurrences.id, input.occurrenceId));
      return { success: true };
    }),

  resolveAllOccurrences: protectedProcedure
    .input(z.number())
    .mutation(async ({ ctx, input }) => {
      const isLeader = await isLeaderOfSchedule(ctx.user.id, input);
      if (!isLeader) throw new TRPCError({ code: "FORBIDDEN", message: "Você não é o líder deste planejamento" });

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      await db.update(scheduleOccurrences)
        .set({ resolved: true })
        .where(and(eq(scheduleOccurrences.scheduleId, input), eq(scheduleOccurrences.resolved, false)));

      return { success: true };
    }),
});
