import { and, desc, eq, gte } from "drizzle-orm";
import type { MySql2Database } from "drizzle-orm/mysql2";

import {
  scheduleOccurrences,
  type ScheduleOccurrence,
  type Shift,
} from "../../drizzle/schema";

export const OCCURRENCE_TYPES = [
  "late",
  "early_exit",
  "absence",
  "client_issue",
  "other",
  "critical",
] as const;

export type OccurrenceType = (typeof OCCURRENCE_TYPES)[number];
export type OccurrenceSeverity = "none" | "medium" | "high";

const typeLabels: Record<OccurrenceType, string> = {
  late: "atraso",
  early_exit: "saida antecipada",
  absence: "falta",
  client_issue: "problema com cliente",
  other: "ocorrencia",
  critical: "critica",
};

const typePluralLabels: Record<OccurrenceType, string> = {
  late: "atrasos",
  early_exit: "saidas antecipadas",
  absence: "faltas",
  client_issue: "problemas com cliente",
  other: "ocorrencias",
  critical: "criticas",
};

const highSeverityTypes = new Set<OccurrenceType>(["absence", "critical"]);

export function getOccurrenceTypeLabel(type: OccurrenceType) {
  return typeLabels[type];
}

export function getOccurrenceSeverity(
  occurrences: Pick<ScheduleOccurrence, "type">[]
): OccurrenceSeverity {
  if (occurrences.length === 0) return "none";
  return occurrences.length >= 3 ||
    occurrences.some(item => highSeverityTypes.has(item.type as OccurrenceType))
    ? "high"
    : "medium";
}

export function summarizeOccurrenceTypes(
  occurrences: Pick<ScheduleOccurrence, "type">[]
) {
  if (occurrences.length === 0) return "Sem ocorrencias";

  const counts = new Map<OccurrenceType, number>();
  for (const occurrence of occurrences) {
    const type = occurrence.type as OccurrenceType;
    counts.set(type, (counts.get(type) || 0) + 1);
  }

  return Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .map(([type, count]) => `${count} ${count === 1 ? typeLabels[type] : typePluralLabels[type]}`)
    .join(", ");
}

export function buildShiftWindow(scheduleDate: Date, shift?: Pick<Shift, "startTime" | "endTime"> | null) {
  const baseDate = new Date(scheduleDate);
  if (!shift?.startTime || !shift?.endTime) {
    const start = new Date(baseDate);
    start.setHours(8, 0, 0, 0);
    const end = new Date(baseDate);
    end.setHours(17, 0, 0, 0);
    return { start, end };
  }

  const start = new Date(baseDate);
  const [startHour, startMinute, startSecond] = shift.startTime.split(":").map(Number);
  start.setHours(startHour || 0, startMinute || 0, startSecond || 0, 0);

  const end = new Date(baseDate);
  const [endHour, endMinute, endSecond] = shift.endTime.split(":").map(Number);
  end.setHours(endHour || 0, endMinute || 0, endSecond || 0, 0);

  if (end.getTime() <= start.getTime()) {
    end.setDate(end.getDate() + 1);
  }

  return { start, end };
}

export function getShiftDurationHours(shift?: Pick<Shift, "startTime" | "endTime"> | null) {
  const { start, end } = buildShiftWindow(new Date("2026-01-01T00:00:00.000Z"), shift);
  return Math.max(1, (end.getTime() - start.getTime()) / (1000 * 60 * 60));
}

type Database = MySql2Database<any>;

type CreateAutomaticOccurrenceInput = {
  db: Database;
  scheduleId: number;
  employeeId: number;
  type: OccurrenceType;
  description: string;
  createdBy: number;
};

export async function createAutomaticOccurrenceIfNeeded({
  db,
  scheduleId,
  employeeId,
  type,
  description,
  createdBy,
}: CreateAutomaticOccurrenceInput) {
  const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const [existing] = await db
    .select()
    .from(scheduleOccurrences)
    .where(
      and(
        eq(scheduleOccurrences.scheduleId, scheduleId),
        eq(scheduleOccurrences.employeeId, employeeId),
        eq(scheduleOccurrences.type, type),
        gte(scheduleOccurrences.createdAt, cutoff)
      )
    )
    .orderBy(desc(scheduleOccurrences.createdAt))
    .limit(1);

  if (existing) {
    return existing;
  }

  const [insertResult] = await db.insert(scheduleOccurrences).values({
    scheduleId,
    employeeId,
    type,
    description,
    autoGenerated: true,
    resolved: false,
    createdBy,
  });

  return {
    id: Number(insertResult.insertId),
    scheduleId,
    employeeId,
    type,
    description,
    autoGenerated: true,
    resolved: false,
    createdBy,
    createdAt: new Date(),
  };
}
